# Starting with Numpy
On this notebook, I'll be going through some basic concepts on Numpy: a Python library that adds support for large multidimensional arrays and high-performance operations with them. <br><br>
First things first. Import Numpy.

In [2]:
import numpy as np
np.set_printoptions(suppress=True) #To change the way floats are printed.

## Axes
Dimensions on Numpy are called **Axes**. So, a 2-dimensional array, has two axes: rows (axis=0) and columns (axis=1)

In [3]:
# Let's create a 3x5 size array.
array = np.arange(15).reshape(3,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
# array has two axes (or two dimensions)
array.ndim

2

In [5]:
# array has 3 elements on first axis, and 5 elements on second axis (3 rows and 5 columns)
array.shape

(3, 5)

In [6]:
# Elements of array are int32 type.
array.dtype.name

'int32'

In [7]:
# array has 15 elements
array.size

15

In [8]:
# sum along axis 0, summarizing all the rows in one row.
array.sum(0)

array([15, 18, 21, 24, 27])

In [9]:
# sum along axis 1, summarizing all the columns.
array.sum(1)

array([10, 35, 60])

## Creating Arrays
There are several ways of creating arrays. Let's see some...

In [10]:
# Using a Python sequence (list or tuple)
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [11]:
# dtype of the array is deduced from the elements of the sequence.
a.dtype.name

'int32'

In [12]:
b = np.array([1.2, 3.4, 2.4])
b.dtype.name

'float64'

In [13]:
# A Python sequence of sequence will create a multidimensional array
c = np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [14]:
# Arrays can also be created with placeholders, specifying the shape. For example, zeros:
z = np.zeros((4,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# or ones
o = np.ones((3,4))
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# or with a sequence of numbers, specifying the step
s = np.arange(4,11,2)
s

array([ 4,  6,  8, 10])

In [17]:
# or specifying number of elements, within a range.
t = np.linspace(0,2,11)
t

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [18]:
#Or using any number as a placeholder, specifying the array's shape.
f = np.full((2,2),6)
f

array([[6, 6],
       [6, 6]])

## Saving and Loading Arrays
Arrays can be saved and loaded in different ways

In [19]:
# Save a single array to a binary npy file
np.save('Data/my_array',a)

# Save multiple arrays to a uncompressed npz file
np.savez('Data/my_arrays',b=b,c=c)

# Save as a plain text file
np.savetxt('Data/my_array_text.txt', array, delimiter='|')

In [20]:
# Load from npy file
a_load = np.load('Data/my_array.npy')
print(a, a_load)

#Load from npz file
data = np.load('Data/my_arrays.npz')
b_load = data['b']
c_load = data['c']
print(b_load)
print(c_load)

#Load from text file
o_load = np.loadtxt('Data/my_array_text.txt', delimiter='|')
print(o_load)

[1 2 3 4] [1 2 3 4]
[1.2 3.4 2.4]
[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]


# Array Mathematics
Some array operations. To make things easy, let's see 2-dimensional array operations.<br>Let's create an some arrays to see this working.

In [21]:
#An array with some manually placed values.
x1 = np.array([[2,1],[3,-1]])
x1.shape

(2, 2)

In [22]:
#An array with identity (shape 2x2)
x2 = np.eye(2)
x2

array([[1., 0.],
       [0., 1.]])

In [23]:
#Matrix sum
x1+x2

array([[3., 1.],
       [3., 0.]])

In [24]:
#Matrix substraction
x1-x2

array([[ 1.,  1.],
       [ 3., -2.]])

In [25]:
#Element wise division
x2/x1

array([[ 0.5,  0. ],
       [ 0. , -1. ]])

In [26]:
#Element wise multiplication
x1*x2

array([[ 2.,  0.],
       [ 0., -1.]])

In [27]:
#Matrix dot product
x1.dot(x2)

array([[ 2.,  1.],
       [ 3., -1.]])

In [28]:
#Exponential of elements of array
np.exp(x1)

array([[ 7.3890561 ,  2.71828183],
       [20.08553692,  0.36787944]])

In [29]:
#Scalar sum and square root of elements of array
np.sqrt(x1+1)

array([[1.73205081, 1.41421356],
       [2.        , 0.        ]])

In [30]:
#Element-wise sine
np.sin((1/2)*x1*np.pi)

array([[ 0.,  1.],
       [-1., -1.]])

In [31]:
#cosine
np.cos((1/2)*x1*np.pi)

array([[-1.,  0.],
       [-0.,  0.]])

In [32]:
#and natural logarithm
np.log(np.exp(x1))

array([[ 2.,  1.],
       [ 3., -1.]])

In [33]:
#Traspose of an array
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
array.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [38]:
#Inverse of a Matrix
x1_i = np.linalg.inv(x1)
x1_i

array([[ 0.2,  0.2],
       [ 0.6, -0.4]])

In [39]:
#Let's check. A matrix dot-multiplied by its inverse, should result in the identity matrix.
x1.dot(x1_i)

array([[ 1., -0.],
       [ 0.,  1.]])